services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  movie-service:
    build: ./movie-service
    container_name: movie-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/movieinsight
      - OMDB_API_KEY=${OMDB_API_KEY}
    depends_on:
      - mongo
    ports:
      - "5001:5001"

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/movieinsight
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    ports:
      - "5002:5002"

  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      - PY_SERVICE=http://movie-service:5001
      - USER_SERVICE=http://user-service:5002
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - movie-service
      - user-service
    ports:
      - "8080:8080"

volumes:
  mongo_data:
